### ISSUE TITLE
push/pop issue in p4v1.1 branch

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4-hlir#10]
Using a push or pop call is causing the retrieve_from_one_action function in the analysis_utils.py file to enter an unexpected state. The push/pop call has a p4_header_stack object as an argument that the function doesn't know how to handle.

 Here's a P4 file (converted to .txt for github) that replicates the issue: [sample.txt](https://github.com/p4lang/p4-hlir/files/292154/sample.txt)

**Comment by antoninbas** [comment]
Hi Robert,
Thanks for reporting this. I fixed it with 1fff5a013a47168b01563c2c1af7de766e9bd3d8
