### ISSUE TITLE
header_type attribute of p4_header_stack is a string

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4-hlir#11]
After building the HLIR the _header_type_ attribute for _p4_header_stack_ objects is a string. I was expecting it to be a _p4_header_ object.

I had a quick look at the code and it seems like the _header_type_ should be updated when the _build()_ method is called, but I don't see where the _build()_ method is ever called. Should https://github.com/p4lang/p4-hlir/blob/p4v1.1/p4_hlir/hlir/p4.py#L103 include **hlir.p4_header_stacks**?

**Comment by antoninbas** [comment]
Fixed by df1dd0415e238aa3e464ef24e730d49bfb0cbf41
