### ISSUE TITLE
Wrong action params references in ternary operator's conditional expressions

### ISSUE THREAD

**Issue by shouxi** [p4lang/p4-hlir#14]
Hi @antoninbas , a new bug follows #13 
IIRC, the right reference of an action param is in the form of 

> {"type":"runtime_data", "value": param_index}. 

But, 

> {"type": "hexstr", "value": hexstr(param_index)} 

is given, if the param is used by a ternary operator.  See L436 of the following json file as an example.

[simple_router.json.txt](https://github.com/p4lang/p4-hlir/files/416771/simple_router.json.txt)
[simple_router.p4.txt](https://github.com/p4lang/p4-hlir/files/416772/simple_router.p4.txt)

**Comment by antoninbas** [comment]
hopefully fixed by f5f41af30ad650eeab3c69df164a0a47b15547a3

**Comment by shouxi** [comment]
Works. Cheers!  BTW, what is the difference between `local` and `runtime_data`?  they both act as param references?

**Comment by antoninbas** [comment]
expression support was added late in bmv2. So a direct reference to an action parameter (e.g. `hdrA.f1 = param1`) is treated a little differently from a reference in an expression (e.g. `hdrA.f1 = param1 + 7`).
In the first case, you will see a `runtime_data` in the JSON. In the second case, the assignment will take as the source an `expression` and the parameter reference will appear as `local`. `local` in expression is a little more generic than just for handling runtime data in actions. It can be used for other things. For example, I may be using it in the parser code to compute the length of a variable length field (in this case `local` is used for previously extracted fields in the header). In other words, `local` can be used to represent arbitrary variables in an expression, whose value does not need to be known until the expression is evaluated.
