### ISSUE TITLE
fatal error: core.p4: No such file or directory

### ISSUE THREAD

**Issue by yuan-128** [p4lang/p4-hlir#38]
myp4@myp4-VM:~/p4-hlir$ p4-validate basic.p4
Preprocessor error on /home/myp4/p4-hlir/basic.p4: 
/home/myp4/p4-hlir/basic.p4:2:19: fatal error: core.p4: No such file or directory
compilation terminated.

myp4@myp4-VM:~/p4-hlir$

**Comment by jnfoster** [comment]
It sounds like you are trying to run this on a P4_16 program.

p4-hlir only handles P4_14.

**Comment by yuan-128** [comment]
Thanks for the reply.
