### ISSUE TITLE
p4-hlir v1.1 reports ``Semantic error'' when checking the semantic of field_list. 

### ISSUE THREAD

**Issue by shouxi** [p4lang/p4-hlir#9]
The tutorial of [copy_to_cpu ](https://github.com/p4lang/tutorials/tree/master/examples/copy_to_cpu) is a showcase. (See [copy_to_cpu.p4.txt](https://github.com/p4lang/p4-hlir/files/287944/copy_to_cpu.p4.txt) for the v1.1-compatible p4 code).  p4c_bm would report: 

> Semantic error: : In file  ***: invalid entry of type 'metadata standard_metadata_t' in field list
> 1 errors during semantic checking
> Interrupting compilation
> Error while building HLIR

**Comment by antoninbas** [comment]
Hi Shouxi,
Thanks for reporting this, it was fixed in 07cb759a0bd4ee2a8f02fcde525c894d578292be

**Comment by shouxi** [comment]
Cheers!

**Comment by shahbhoomi** [comment]
Hi I am getting this same error while compiling my program. I am very new and so just trying to figure out the reason. Can you please tell me what does this error mean. Can you please tell me what causes this error? I tried searching but this is the only link which shows my exact error. 

[hlir](https://cloud.githubusercontent.com/assets/16211732/16020717/240b7f10-3164-11e6-833b-d08d9becd73f.png)

**Comment by shouxi** [comment]
Hi @shahbhoomi, as is reported 

> Semantic error: P4 program does not define a start parse state

It seems that your P4 program has not specified the start function for parsing. 
According to the P4 spec (see 17.1 Programming Conventions, v1.1), 

> Parsing begins with the parser state function named **start**.

you definitely should add it. Refer to [this](https://github.com/p4lang/tutorials/blob/master/p4v1_1/simple_router/p4src/simple_router.p4#L41) as an example.
